name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Stamp version
        run: |
          sed -i "s/@@VERSION_PLACEHOLDER@@/2.0.0.dev1/g" qpython/__init__.py

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.14.1

      - name: Build wheels
        env:
          CIBW_BUILD: "cp311-manylinux_x86_64"
          CIBW_BEFORE_BUILD_LINUX: "bash .github/workflows/scripts/build_setup.sh"
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl