name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Stamp version
        run: |
          sed -i "s/@@VERSION_PLACEHOLDER@@/2.0.0.dev1/g" qpython/__init__.py

      - uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install -r requirements.txt -U
          pip install build wheel

      - name: Build wheel
        run: python -m build --wheel --outdir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl